### ISSUE TITLE
Bugs exercise

### ISSUE THREAD

**Issue by yasinabdmahmood** [kusiLaw/portfolio#13]
Great job implementing the mobile menu project, but I noticed a bug in your code, when you click on the hamburger button and then click on the exit icon to close the menu after that if you resize your screen the hamburger icon stays  for desktop design instead of disappearing as shown in the recording below .

https://user-images.githubusercontent.com/97350474/181817584-12c3d410-0755-4a02-8403-718c5782e2d9.mp4

I suggest replacing line 65 in your toggle-menu.js file 
from
**btnMob.style.display = 'none';**
to
**btnMob.style.visibility = 'hidden';**

**Comment by kusiLaw** [comment]
Bug fixed. Thank you
